=== seb-gonzalez/Jenkins-quality-metrics/src/main/api/schemas/companies.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "title": "Companies",
  "description": "A list of companies returned from D&B",
  "items": {
    "type": "object",
    "title": "Company",
    "description": "A company object",
    "properties": {
      "address": {
        "type": "string",
        "title": "Business Address",
        "description": "Registered postal address of the company"
      },
      "duns": {
        "type": "string",
        "title": "D-U-N-S Number",
        "description": "A unique nine digit identification number",
        "minLength": 9,
        "maxLength": 9
      },
      "name": {
        "type": "string",
        "title": "Company Name",
        "description": "The offical name of the company"
      },
      "town": {
        "type": "string",
        "title": "Town",
        "description": "The registered town of the company"
      },
      "postcode": {
        "type": "string",
        "title": "Postcode",
        "description": "The registered postal code of the company"
      },
      "telephone": {
        "type": "string",
        "title": "Telephone",
        "description": "The registered phone number of the company"
      }
    },
    "required": [
      "address",
      "duns",
      "name",
      "town",
      "postcode"
    ]
  }
}

=== seb-gonzalez/Jenkins-quality-metrics/src/main/api/.repository/examples/companies.json
[
  {
    "address": "35-37 William Road, Camden Town",
    "duns": "211610084",
    "name": "ADDISON LEE LIMITED",
    "town": "LONDON",
    "postcode": "NW1 3ER",
    "telephone": "02076577777"
  },
  {
    "address": "35-37 William Road",
    "duns": "219365938",
    "name": "ADDISON LEE GROUP LIMITED",
    "town": "LONDON",
    "postcode": "NW1 3ER"
  },
  {
    "address": "35-37 WILLIAM ROAD",
    "duns": "779194260",
    "name": "ADDISON LEE COACHES LIMITED",
    "town": "LONDON",
    "postcode": "NW1 3ER",
    "telephone": "02073878888"
  },
  {
    "address": "35-37 William Road",
    "duns": "219365685",
    "name": "ADDISON LEE HOLDINGS LIMITED",
    "town": "LONDON",
    "postcode": "NW1 3ER"
  },
  {
    "address": "35-37 William Road",
    "duns": "217826693",
    "name": "Addison Lee Limited",
    "town": "London",
    "postcode": "NW1 3ER",
    "telephone": "02073878888"
  },
  {
    "address": "728 HIGH Rd",
    "duns": "294603261",
    "name": "ADDISON-LEE NORTH LIMITED",
    "town": "LONDON",
    "postcode": "N12 0BP",
    "telephone": "01717940515"
  },
  {
    "address": "45-46 CHANDOS PL",
    "duns": "227341252",
    "name": "ADDISON-LEE COURIERS LIMITED",
    "town": "LONDON",
    "postcode": "WC2N 4HS",
    "telephone": "01713797000"
  },
  {
    "address": "35-37 William Road",
    "duns": "219980914",
    "name": "JPG TRAINING LIMITED",
    "town": "LONDON",
    "postcode": "NW1 3ER",
    "telephone": "02073878888"
  },
  {
    "address": "35-37 William Road",
    "duns": "219365854",
    "name": "ADDISON LEE FINANCING LIMITED",
    "town": "LONDON",
    "postcode": "NW1 3ER"
  },
  {
    "address": "35-37 William Road",
    "duns": "219365738",
    "name": "ADDISON LEE MIDCO I LIMITED",
    "town": "LONDON",
    "postcode": "NW1 3ER",
    "telephone": "01618728104"
  },
  {
    "address": "35-37 William Road",
    "duns": "219365800",
    "name": "ADDISON LEE MIDCO II LIMITED",
    "town": "LONDON",
    "postcode": "NW1 3ER",
    "telephone": "01618728104"
  },
  {
    "address": "26 Church Street",
    "duns": "500232426",
    "name": "ADDISON LONDON LIMITED",
    "town": "BISHOPS STORTFORD",
    "postcode": "CM23 2LY",
    "telephone": "01932856721"
  },
  {
    "address": "STRATHDEVERON HOUSE STEVEN ROAD",
    "duns": "239528206",
    "name": "ADDISON ELECTRICAL LIMITED",
    "town": "HUNTLY",
    "postcode": "AB54 8SX",
    "telephone": "01466751607"
  },
  {
    "address": "Leopard House Asama Court",
    "duns": "212780829",
    "name": "ADDISON MOTORS LIMITED",
    "town": "NEWCASTLE-UPON-TYNE",
    "postcode": "NE4 7YD",
    "telephone": "01912981410"
  },
  {
    "address": "REGINA HOUSE 124 FINCHLEY ROAD",
    "duns": "220402616",
    "name": "ADDISON PROPERTY COMPANY LIMITED",
    "town": "LONDON",
    "postcode": "NW3 5JS"
  },
  {
    "address": "THE ESTATE OFFICE MELBURY SAMPFORD",
    "duns": "896777299",
    "name": "ADDISON DEVELOPMENTS LIMITED",
    "town": "DORCHESTER",
    "postcode": "DT2 0LF"
  },
  {
    "address": "Pendower House Northumberland Road Cumberland Business Centre",
    "duns": "225561869",
    "name": "Addison Madden",
    "town": "SOUTHSEA",
    "postcode": "PO5 1DS",
    "telephone": "02392830815"
  },
  {
    "address": "The Estate Office Melbury Sampford",
    "duns": "217386724",
    "name": "ADDISON DEVELOPMENTS THREE LIMITED",
    "town": "DORCHESTER",
    "postcode": "DT2 0LF"
  },
  {
    "address": "49 Southwark Bridge Road",
    "duns": "211611041",
    "name": "ADDISON CORPORATE MARKETING LIMITED",
    "town": "LONDON",
    "postcode": "SE1 9HH",
    "telephone": "02078152000"
  },
  {
    "address": "Ebor House 91 Galgate",
    "duns": "368305603",
    "name": "Addison & Co Chartered Accountants Ltd",
    "town": "BARNARD CASTLE",
    "postcode": "DL12 8ES",
    "telephone": "01833690202"
  },
  {
    "address": "6 HELVELLYN CLOSE",
    "duns": "424224405",
    "name": "AMBERSMART LIMITED",
    "town": "EGHAM",
    "postcode": "TW20 8JQ"
  },
  {
    "address": "Bruce Kenrick House 2 Killick Street",
    "duns": "232061374",
    "name": "NOTTING HILL HOME OWNERSHIP LTD",
    "town": "LONDON",
    "postcode": "N1 9FL",
    "telephone": "02083574499"
  },
  {
    "address": "4 Petre Road, Clayton Business Park Clayton-le-moors",
    "duns": "210161032",
    "name": "DIALACHEMIST LIMITED",
    "town": "ACCRINGTON",
    "postcode": "BB5 5JB",
    "telephone": "08455240047"
  },
  {
    "address": "Edinburgh Gate",
    "duns": "210184776",
    "name": "PEARSON EDUCATION LIMITED",
    "town": "HARLOW",
    "postcode": "CM20 2JE",
    "telephone": "01279623623"
  }
]
